import {
  Payment,
  ReconciliationMatch,
  BankTransactionSummary,
} from './reconciliation.models';

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(today.getDate() - n);
  return d.toISOString();
};

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 1,
    externalId: 'pi_001',
    amount: 178.5,
    currency: 'USD',
    paymentDate: daysAgo(1),
    method: 'Card',
    last4: '4242',
    guestName: 'Sarah Thompson',
    reservationId: 'RV-1245',
    reconciled: true,
    source: 'rfbooks',
  },
  {
    id: 2,
    externalId: 'pi_002',
    amount: 642.0,
    currency: 'USD',
    paymentDate: daysAgo(2),
    method: 'ACH',
    last4: null,
    guestName: 'Mark & Jenna Lewis',
    reservationId: 'CAB-87',
    reconciled: true,
    source: 'rfbooks',
  },
  {
    id: 3,
    externalId: 'pi_003',
    amount: 82.0,
    currency: 'USD',
    paymentDate: daysAgo(3),
    method: 'Card',
    last4: '1111',
    guestName: 'Daniel H.',
    reservationId: 'TENT-331',
    reconciled: false,
    source: 'rfbooks',
  },
  {
    id: 4,
    externalId: 'pi_004',
    amount: 245.75,
    currency: 'USD',
    paymentDate: daysAgo(4),
    method: 'Card',
    last4: '5678',
    guestName: 'Jessica Martinez',
    reservationId: 'CAB-92',
    reconciled: false,
    source: 'rfbooks',
  },
  {
    id: 5,
    externalId: 'pi_005',
    amount: 156.00,
    currency: 'USD',
    paymentDate: daysAgo(5),
    method: 'ACH',
    last4: null,
    guestName: 'Robert Chen',
    reservationId: 'RV-1250',
    reconciled: false,
    source: 'rfbooks',
  },
  {
    id: 6,
    externalId: 'pi_006',
    amount: 320.00,
    currency: 'USD',
    paymentDate: daysAgo(6),
    method: 'Card',
    last4: '9012',
    guestName: 'Emily & James Wilson',
    reservationId: 'TENT-335',
    reconciled: false,
    source: 'rfbooks',
  },
];

const MOCK_BANK_TRANSACTIONS: BankTransactionSummary[] = [
  {
    id: 101,
    transactionId: 'tx_001',
    amount: 178.5,
    currency: 'USD',
    transactionDate: daysAgo(1),
    description: 'Visa Settlement · Sarah T.',
    source: 'plaid',
  },
  {
    id: 102,
    transactionId: 'tx_002',
    amount: 642.0,
    currency: 'USD',
    transactionDate: daysAgo(2),
    description: 'ACH Deposit · Lewis Family',
    source: 'plaid',
  },
  {
    id: 103,
    transactionId: 'tx_003',
    amount: 245.75,
    currency: 'USD',
    transactionDate: daysAgo(4),
    description: 'Online Payment Receipt',
    source: 'plaid',
  },
  {
    id: 104,
    transactionId: 'tx_004',
    amount: 156.00,
    currency: 'USD',
    transactionDate: daysAgo(5),
    description: 'ACH Transfer - Chen',
    source: 'plaid',
  },
  {
    id: 105,
    transactionId: 'tx_005',
    amount: 320.00,
    currency: 'USD',
    transactionDate: daysAgo(6),
    description: 'Card Payment - Wilson',
    source: 'plaid',
  },
  {
    id: 106,
    transactionId: 'tx_006',
    amount: 99.50,
    currency: 'USD',
    transactionDate: daysAgo(7),
    description: 'Mystery Transaction',
    source: 'plaid',
  },
];

export const MOCK_MATCHES: ReconciliationMatch[] = [
  {
    id: 1001,
    status: 'MATCHED',
    differenceAmount: 0,
    reason: 'Matched by date + amount',
    payment: MOCK_PAYMENTS[0],
    bankTransaction: MOCK_BANK_TRANSACTIONS[0],
    createdAt: daysAgo(0),
  },
  {
    id: 1002,
    status: 'MATCHED',
    differenceAmount: 0,
    reason: 'Matched by date + amount',
    payment: MOCK_PAYMENTS[1],
    bankTransaction: MOCK_BANK_TRANSACTIONS[1],
    createdAt: daysAgo(0),
  },
  {
    id: 1003,
    status: 'UNMATCHED_PAYMENT',
    differenceAmount: MOCK_PAYMENTS[2].amount,
    reason: 'No bank transaction found in date window',
    payment: MOCK_PAYMENTS[2],
    bankTransaction: null,
    createdAt: daysAgo(0),
  },
  {
    id: 1004,
    status: 'UNMATCHED_PAYMENT',
    differenceAmount: MOCK_PAYMENTS[3].amount,
    reason: 'Amount matches but description unclear',
    payment: MOCK_PAYMENTS[3],
    bankTransaction: null,
    createdAt: daysAgo(0),
  },
  {
    id: 1005,
    status: 'UNMATCHED_PAYMENT',
    differenceAmount: MOCK_PAYMENTS[4].amount,
    reason: 'No bank transaction found',
    payment: MOCK_PAYMENTS[4],
    bankTransaction: null,
    createdAt: daysAgo(0),
  },
  {
    id: 1006,
    status: 'UNMATCHED_PAYMENT',
    differenceAmount: MOCK_PAYMENTS[5].amount,
    reason: 'No bank transaction found',
    payment: MOCK_PAYMENTS[5],
    bankTransaction: null,
    createdAt: daysAgo(0),
  },
  {
    id: 1007,
    status: 'UNMATCHED_BANK_TRANSACTION',
    differenceAmount: MOCK_BANK_TRANSACTIONS[2].amount,
    reason: 'No payment record found',
    payment: null,
    bankTransaction: MOCK_BANK_TRANSACTIONS[2],
    createdAt: daysAgo(0),
  },
  {
    id: 1008,
    status: 'UNMATCHED_BANK_TRANSACTION',
    differenceAmount: MOCK_BANK_TRANSACTIONS[3].amount,
    reason: 'No payment record found',
    payment: null,
    bankTransaction: MOCK_BANK_TRANSACTIONS[3],
    createdAt: daysAgo(0),
  },
  {
    id: 1009,
    status: 'UNMATCHED_BANK_TRANSACTION',
    differenceAmount: MOCK_BANK_TRANSACTIONS[4].amount,
    reason: 'No payment record found',
    payment: null,
    bankTransaction: MOCK_BANK_TRANSACTIONS[4],
    createdAt: daysAgo(0),
  },
  {
    id: 1010,
    status: 'UNMATCHED_BANK_TRANSACTION',
    differenceAmount: MOCK_BANK_TRANSACTIONS[5].amount,
    reason: 'Unknown source - needs investigation',
    payment: null,
    bankTransaction: MOCK_BANK_TRANSACTIONS[5],
    createdAt: daysAgo(0),
  },
];
