name: rf-books

services:
  postgres:
    image: postgres:15
    container_name: rfbooks-postgres
    environment:
      POSTGRES_DB: rfbooks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - rfbooks-data:/var/lib/postgresql/data
      - ./01-init-all.sql:/docker-entrypoint-initdb.d/01-init-all.sql
    networks:
      - rfbooks-network

volumes:
  rfbooks-data:
    driver: local

networks:
  rfbooks-network:
    driver: bridge
