# RF Books Spring Boot backend
server.port=8081

plaid.client-id=693755f5f1a1190023729ef4
plaid.secret=ed0c5480552215d340ef37eb99aa6f
plaid.environment=sandbox

# CORS
#spring.web.cors.allowed-origins=http://localhost:4200
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# H2 Console (optional, for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:postgresql://localhost:5432/rfbooks
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


